// <auto-generated />
using CoursePlanner_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoursePlanner_Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250422145500_seedData")]
    partial class seedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CampusCourse", b =>
                {
                    b.Property<int>("CampusesId")
                        .HasColumnType("int");

                    b.Property<int>("CoursesId")
                        .HasColumnType("int");

                    b.HasKey("CampusesId", "CoursesId");

                    b.HasIndex("CoursesId");

                    b.ToTable("CampusCourse");

                    b.HasData(
                        new
                        {
                            CampusesId = 4,
                            CoursesId = 1
                        },
                        new
                        {
                            CampusesId = 4,
                            CoursesId = 2
                        },
                        new
                        {
                            CampusesId = 4,
                            CoursesId = 3
                        },
                        new
                        {
                            CampusesId = 4,
                            CoursesId = 4
                        },
                        new
                        {
                            CampusesId = 1,
                            CoursesId = 4
                        },
                        new
                        {
                            CampusesId = 4,
                            CoursesId = 5
                        });
                });

            modelBuilder.Entity("CourseFeature", b =>
                {
                    b.Property<int>("CoursesId")
                        .HasColumnType("int");

                    b.Property<int>("FeaturesId")
                        .HasColumnType("int");

                    b.HasKey("CoursesId", "FeaturesId");

                    b.HasIndex("FeaturesId");

                    b.ToTable("CourseFeature");
                });

            modelBuilder.Entity("CoursePlanner_Backend.Model.Entities.Campus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Campuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Hamilton"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Middletown"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Oxford"
                        },
                        new
                        {
                            Id = 5,
                            Name = "West Chester"
                        });
                });

            modelBuilder.Entity("CoursePlanner_Backend.Model.Entities.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("courseId")
                        .HasColumnType("int");

                    b.Property<int>("scheduleId")
                        .HasColumnType("int");

                    b.Property<string>("semester")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("courseId");

                    b.HasIndex("scheduleId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("CoursePlanner_Backend.Model.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Course_Number")
                        .HasColumnType("int");

                    b.Property<double>("Credit_Hours")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreRequisites")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Course_Number = 135,
                            Credit_Hours = 3.0,
                            Description = "Develops fundamentals of analyzing, organizing, adapting, and delivering ideas effectively in public contexts. Special emphasis placed upon informative and persuasive discourse.",
                            Name = "Principles of Public Speaking",
                            PreRequisites = "",
                            Subject = "STC"
                        },
                        new
                        {
                            Id = 2,
                            Course_Number = 231,
                            Credit_Hours = 3.0,
                            Description = "Theoretical issues that affect communication between members of work teams, discussion groups, and decision-making bodies. Students study these theories and related research studies and work as members of student teams to analyze critically both the theoretical and practical implications of the theories and research studies.",
                            Name = "Small Group Communication",
                            PreRequisites = "",
                            Subject = "APC"
                        },
                        new
                        {
                            Id = 3,
                            Course_Number = 151,
                            Credit_Hours = 4.0,
                            Description = "Topics include limits and continuity, derivatives and their applications, and early integration techniques of polynomial, rational, radical, trigonometric, inverse trigonometric, exponential, and logarithmic functions. It is expected that students have completed a trigonometry or pre-calculus course and possess the following pre-requisite knowledge: factoring polynomials, working with fractional exponents, finding the domain of functions, properties of common functions such as polynomial, absolute value, exponential, logarithmic, trigonometric, and rational functions, solving a variety of types of equations, inverse functions, graphing, and other related topics",
                            Name = "Calculus I",
                            PreRequisites = "",
                            Subject = "MTH"
                        },
                        new
                        {
                            Id = 4,
                            Course_Number = 231,
                            Credit_Hours = 3.0,
                            Description = "Service course. Topics, techniques and terminology in discrete mathematics: logic, sets, proof by mathematical induction, relations, counting. Credit does not count toward a major in the department of Mathematics or Statistics.",
                            Name = "Elements of Discrete Mathematics",
                            PreRequisites = "",
                            Subject = "MTH"
                        },
                        new
                        {
                            Id = 5,
                            Course_Number = 331,
                            Credit_Hours = 3.0,
                            Description = "Designed to ease the transition to 400-level courses in mathematics and statistics. The emphasis of the course is on writing and analyzing mathematical proofs. Topics covered will be foundational for higher level courses and will include propositional and predicate logic, methods of proof, induction, sets, relations, and functions.",
                            Name = "Proof: Introduction to Higher Mathematics",
                            PreRequisites = "",
                            Subject = "MTH"
                        });
                });

            modelBuilder.Entity("CoursePlanner_Backend.Model.Entities.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Short_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Features");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Advanced Writing",
                            Short_Name = "PA"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Creative Arts",
                            Short_Name = "PA"
                        });
                });

            modelBuilder.Entity("CoursePlanner_Backend.Model.Entities.Major", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("College")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Credit_Max")
                        .HasColumnType("float");

                    b.Property<double>("Credit_Min")
                        .HasColumnType("float");

                    b.Property<bool>("Graduate")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Majors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            College = "College of Computer Science",
                            Credit_Max = 98.0,
                            Credit_Min = 92.0,
                            Graduate = false,
                            Name = "Software Engineering"
                        });
                });

            modelBuilder.Entity("CoursePlanner_Backend.Model.Entities.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("userId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("CoursePlanner_Backend.Model.Entities.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Credit_Max")
                        .HasColumnType("float");

                    b.Property<double>("Credit_Min")
                        .HasColumnType("float");

                    b.Property<int>("MajorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MajorId");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("CoursePlanner_Backend.Model.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Admin")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Admin = false,
                            Email = "Email@Email.com",
                            Password = "Password",
                            Username = "Username"
                        });
                });

            modelBuilder.Entity("CourseSection", b =>
                {
                    b.Property<int>("CoursesId")
                        .HasColumnType("int");

                    b.Property<int>("SectionsId")
                        .HasColumnType("int");

                    b.HasKey("CoursesId", "SectionsId");

                    b.HasIndex("SectionsId");

                    b.ToTable("CourseSection");
                });

            modelBuilder.Entity("CampusCourse", b =>
                {
                    b.HasOne("CoursePlanner_Backend.Model.Entities.Campus", null)
                        .WithMany()
                        .HasForeignKey("CampusesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoursePlanner_Backend.Model.Entities.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CourseFeature", b =>
                {
                    b.HasOne("CoursePlanner_Backend.Model.Entities.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoursePlanner_Backend.Model.Entities.Feature", null)
                        .WithMany()
                        .HasForeignKey("FeaturesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CoursePlanner_Backend.Model.Entities.Class", b =>
                {
                    b.HasOne("CoursePlanner_Backend.Model.Entities.Course", "course")
                        .WithMany("Classes")
                        .HasForeignKey("courseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoursePlanner_Backend.Model.Entities.Schedule", "schedule")
                        .WithMany("classes")
                        .HasForeignKey("scheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("course");

                    b.Navigation("schedule");
                });

            modelBuilder.Entity("CoursePlanner_Backend.Model.Entities.Schedule", b =>
                {
                    b.HasOne("CoursePlanner_Backend.Model.Entities.User", "user")
                        .WithMany("schedules")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("CoursePlanner_Backend.Model.Entities.Section", b =>
                {
                    b.HasOne("CoursePlanner_Backend.Model.Entities.Major", "Major")
                        .WithMany("Sections")
                        .HasForeignKey("MajorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Major");
                });

            modelBuilder.Entity("CourseSection", b =>
                {
                    b.HasOne("CoursePlanner_Backend.Model.Entities.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoursePlanner_Backend.Model.Entities.Section", null)
                        .WithMany()
                        .HasForeignKey("SectionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CoursePlanner_Backend.Model.Entities.Course", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("CoursePlanner_Backend.Model.Entities.Major", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("CoursePlanner_Backend.Model.Entities.Schedule", b =>
                {
                    b.Navigation("classes");
                });

            modelBuilder.Entity("CoursePlanner_Backend.Model.Entities.User", b =>
                {
                    b.Navigation("schedules");
                });
#pragma warning restore 612, 618
        }
    }
}
